name: build sgsi

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM link'
        required: true
        default: 'https://bigota.d.miui.com/V12.5.10.0.RGGINXM/miui_BEGONIAININGlobal_V12.5.10.0.RGGINXM_4716f60949_11.0.zip'
      ZIP_NAME:
        description: 'ZIP name (The name of the file which you just put link above.)'
        required: true
        default: 'miui_BEGONIAININGlobal_V12.5.10.0.RGGINXM_4716f60949_11.0.zip'
      OS_TYPE:
        description: 'OS type (Generic, Pixel, MIUI, Flyme, ColorOS, RogUI, JoyUI, VOS, Nubia, Moto, MyOS, OxygenOS, RedMagicOS)'
        required: true
        default: 'MIUI'
      REPACK_NAME:
        description: 'Repack name (OutPut file name.)'
        required: true
        default: 'test'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get the source code of this repository...
        uses: actions/checkout@main
      - name: Preparing stuff...
        run: |
          sudo apt update && sudo apt-get install -y git unzip curl aria2 expect

      - name: Get the SGSI tool‌‌...
        run: |
          git clone --recurse-submodules https://github.com/As9124k82134/SGSI-Build-Tool.git -b main11 $GITHUB_WORKSPACE/Tool-SGSI-build

      - name: Setup tool environment...
        run: |
          sudo bash $GITHUB_WORKSPACE/Tool-SGSI-build/setup.sh
          sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"

      - name: Build SGSI...
        run: |
          sudo bash $GITHUB_WORKSPACE/Tool-SGSI-build/url2SGSI.sh ${{ github.event.inputs.ROM_URL }} ${{ github.event.inputs.OS_TYPE }}:${{ github.event.inputs.REPACK_NAME }}
          
      - name: Repack output file...
        run: |            
          cd $GITHUB_WORKSPACE/Tool-SGSI-build
          sudo chmod -R 777 output ; cd output
          gzip -qf9 *img
          sudo rm -rf *.img          
          
      - name: Upload SGSI to WeTransfer...
        run: |
          cd $GITHUB_WORKSPACE/Tool-SGSI-build/output
          curl -sL https://git.io/file-transfer | sh
          ./transfer wet /*.img.gz
